# "Instrucciones versión 3.8" 
services:
  # --- 1. El servicio de Base de Datos ---
  db:
    image: mariadb:latest
    container_name: mi_base_de_datos
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../datos_db:/var/lib/mysql
    networks:
      - mi_red_local

  # --- 2. El servicio de phpMyAdmin 
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mi_phpmyadmin
    restart: unless-stopped
    ports:
      # Lo verás en: http://localhost:8080
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - mi_red_local
    depends_on:
      - db

 
  api:
   
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mi_api_flask
    restart: unless-stopped
    ports:
      # Expone el puerto 5000 de tu app
      # Lo verás en: http://localhost:5000
      - "5000:5000"
    networks:
      - mi_red_local
    # Le decimos que no inicie hasta que la 'db' esté lista
    depends_on:
      - db
    # Le decimos que cargue las variables de tu config.env
    env_file:
      - ../config.env

  # --- 4. ¡NUEVO! Tu Dashboard Frontend (Nginx) ---
  dashboard_frontend:
    image: nginx:alpine
    container_name: mi_dashboard_frontend
    restart: unless-stopped
    ports:
      # Lo verás en: http://localhost:8082 (CAMBIADO de 8081 a 8082)
      - "8082:80"
    volumes:
      # Montamos la carpeta de estadísticas
      - ../frontend/Estadisticas/estadistica:/usr/share/nginx/html
      # Montamos la configuración de Nginx
      - ../frontend/Estadisticas/estadistica/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mi_red_local
    depends_on:
      - api

networks:
  mi_red_local:
    driver: bridge
